[CmdletBinding()]
param(
    [string]$SkillRoot,
    [string]$ReviewDate = (Get-Date -Format 'yyyy-MM-dd'),
    [string]$SubmissionCsvPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($SkillRoot)) {
    $scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
    $SkillRoot = Split-Path -Parent $scriptDirectory
}

function Get-Slug {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    $slug = $Value.ToLowerInvariant()
    $slug = [regex]::Replace($slug, '[^a-z0-9]+', '-')
    $slug = $slug.Trim('-')

    if ([string]::IsNullOrWhiteSpace($slug)) {
        return 'item'
    }

    return $slug
}

function ConvertTo-YamlList {
    param(
        [string[]]$Items
    )

    if (-not $Items -or $Items.Count -eq 0) {
        return "  - resume`n"
    }

    return (($Items | ForEach-Object { "  - $_" }) -join "`n") + "`n"
}

$tipsRoot = Join-Path $SkillRoot 'tips'
$inboxRoot = Join-Path $tipsRoot 'inbox'
$reviewedRoot = Join-Path $tipsRoot 'reviewed'
$archiveRoot = Join-Path $tipsRoot 'archive'
$sourcesPath = Join-Path $tipsRoot 'sources.json'
$weeklyPacketPath = Join-Path $tipsRoot ("weekly-review-{0}.md" -f $ReviewDate)

foreach ($path in @($tipsRoot, $inboxRoot, $reviewedRoot, $archiveRoot)) {
    if (-not (Test-Path -LiteralPath $path)) {
        New-Item -ItemType Directory -Path $path | Out-Null
    }
}

if (-not (Test-Path -LiteralPath $sourcesPath)) {
    throw "Missing source roster: $sourcesPath"
}

$sources = Get-Content -LiteralPath $sourcesPath -Raw | ConvertFrom-Json
$activeSources = @($sources | Where-Object { $_.active -eq $true })

$packet = New-Object System.Collections.Generic.List[string]
$packet.Add("# Resume Tips Weekly Review - $ReviewDate")
$packet.Add("")
$packet.Add('Generated by `scripts/Invoke-ResumeTipsRefresh.ps1`.')
$packet.Add("")
$packet.Add("## Goals")
$packet.Add("")
$packet.Add("- Check each active source for fresh recruiter, HR, or hiring-manager guidance relevant to resumes.")
$packet.Add('- Add strong candidates to `tips/inbox/`.')
$packet.Add('- Move weak or stale items to `tips/archive/` during review.')
$packet.Add('- Promote only durable patterns into `insights/principles.md` after review.')
$packet.Add("")
$packet.Add("## Active Sources")
$packet.Add("")

foreach ($source in $activeSources) {
    $packet.Add(("### {0}" -f $source.name))
    $packet.Add("")
    $packet.Add(("- Platform: {0}" -f $source.platform))
    $packet.Add(("- Discovery URL: {0}" -f $source.discoveryUrl))
    $packet.Add(("- Focus: {0}" -f (($source.focus) -join ', ')))
    $packet.Add(("- Notes: {0}" -f $source.notes))
    $packet.Add("- Review status: [ ] Checked this week")
    $packet.Add("- Candidate posts captured: [ ] None yet")
    $packet.Add("")
}

$createdFiles = New-Object System.Collections.Generic.List[string]

if ($SubmissionCsvPath) {
    if (-not (Test-Path -LiteralPath $SubmissionCsvPath)) {
        throw "Submission CSV not found: $SubmissionCsvPath"
    }

    $rows = Import-Csv -LiteralPath $SubmissionCsvPath

    foreach ($row in $rows) {
        $sourceName = if ($row.source_name) { $row.source_name } else { 'Unknown source' }
        $title = if ($row.title) { $row.title } else { 'Untitled post' }
        $publishedAt = if ($row.published_at) { $row.published_at } else { $ReviewDate }
        $sourceUrl = if ($row.url) { $row.url } else { '' }
        $topics = @()

        if ($row.topics) {
            $topics = @($row.topics -split '\s*[,;|]\s*' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        }

        $slug = Get-Slug -Value ("{0}-{1}" -f $ReviewDate, $title)
        $outputPath = Join-Path $inboxRoot ("{0}.md" -f $slug)

        if (Test-Path -LiteralPath $outputPath) {
            continue
        }

        $content = @(
            '---'
            ("source_name: {0}" -f $sourceName)
            ("source_type: {0}" -f $(if ($row.source_type) { $row.source_type } else { 'unknown' }))
            ("source_url: {0}" -f $sourceUrl)
            ("published_at: {0}" -f $publishedAt)
            ("captured_at: {0}" -f $ReviewDate)
            'topics:'
            (ConvertTo-YamlList -Items $topics).TrimEnd("`n")
            'status: suggested'
            ("confidence: {0}" -f $(if ($row.confidence) { $row.confidence } else { 'medium' }))
            '---'
            ''
            '## Why it matters'
            ''
            $(if ($row.summary) { $row.summary } else { 'Add a short explanation of why this advice matters.' })
            ''
            '## Extracted resume tips'
            ''
            $('- ' + $(if ($row.tip_1) { $row.tip_1 } else { 'Add the first actionable tip here.' }))
            $('- ' + $(if ($row.tip_2) { $row.tip_2 } else { 'Add the second actionable tip here.' }))
            ''
            '## Promotion recommendation'
            ''
            '- [ ] Promote into insights/principles.md'
            '- [ ] Keep in reviewed/'
            '- [ ] Archive'
        ) -join "`n"

        Set-Content -LiteralPath $outputPath -Value $content
        $createdFiles.Add($outputPath) | Out-Null
    }
}

if ($createdFiles.Count -gt 0) {
    $packet.Add("## Imported Candidates")
    $packet.Add("")

    foreach ($file in $createdFiles) {
        $packet.Add(("- {0}" -f (Split-Path -Leaf $file)))
    }

    $packet.Add("")
}

$packet.Add("## Next Actions")
$packet.Add("")
$packet.Add("1. Open the discovery URLs and identify any new posts worth capturing.")
$packet.Add('2. Add the strongest candidates into `tips/inbox/`.')
$packet.Add('3. Review and move keeper notes into `tips/reviewed/`.')
$packet.Add('4. Promote only high-confidence patterns into `insights/principles.md`.')
$packet.Add("")

Set-Content -LiteralPath $weeklyPacketPath -Value ($packet -join "`n")

[pscustomobject]@{
    ReviewDate = $ReviewDate
    WeeklyPacket = $weeklyPacketPath
    ActiveSources = $activeSources.Count
    ImportedCandidates = $createdFiles.Count
}
